name: Master

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build and push Docker image
        run: |
          docker build -t 090678/lp .
          docker push 090678/lp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          password: ${{ secrets.VPS_PASSWORD }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~
            docker system prune -a -f
            docker-compose -f docker-compose-lp.yml down
            docker-compose -f docker-compose-lp.yml rm -f
            docker-compose -f docker-compose-lp.yml pull
            docker-compose -f docker-compose-lp.yml up -d
